// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("NovaData")>]
[<assembly: AssemblyProductAttribute("NovaData")>]
[<assembly: AssemblyDescriptionAttribute("Raw files to ETL")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "NovaData"
    let [<Literal>] AssemblyProduct = "NovaData"
    let [<Literal>] AssemblyDescription = "Raw files to ETL"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
